apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: fintech
type: Opaque
stringData:
  username: "root"
  password: "password"
  url: "jdbc:mysql://my-database-instance.c122egeymo28.us-east-1.rds.amazonaws.com:3306/notification_db"
